/**
 * Header Component
 *
 * Application header with user info display.
 * Generated by `hai3 scaffold layout`.
 */

import React, { useState, useRef, useEffect } from 'react';
import { useAppSelector, useTheme, eventBus, type HeaderState } from '@cyberfabric/react';
import { User, LogOut, Sun, Moon, Monitor, Palette, Settings, KeyRound, AlertTriangle } from 'lucide-react';
import { Avatar, AvatarImage, AvatarFallback } from '@/app/components/primitives/Avatar';
import { Skeleton } from '@/app/components/primitives/Skeleton';
import { logoutAction } from '@/app/actions/bootstrapActions';
import { Urls } from '@/app/api';
import { usePageHeader } from './PageHeader';

export interface HeaderProps {
  children?: React.ReactNode;
}

export const Header: React.FC<HeaderProps> = ({ children }) => {
  const headerState = useAppSelector((state) => state['layout/header'] as HeaderState | undefined);
  const [menuOpen, setMenuOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  const user = headerState?.user;
  const loading = headerState?.loading ?? false;

  const [tokenFailures, setTokenFailures] = useState<{ id: string; serviceType: string; name: string; message: string }[]>([]);

  useEffect(() => {
    const subHealth = eventBus.on('profile/tokens/health', ({ failures }) => {
      setTokenFailures(failures);
    });
    const subValidated = eventBus.on('profile/tokens/validated', ({ id, result }) => {
      setTokenFailures((prev) => {
        const without = prev.filter((f) => f.id !== id);
        if (result.valid) return without;
        return [...without, { id, serviceType: '', name: '', message: result.message }];
      });
    });
    const subAuth = eventBus.on('app/auth/state', ({ authenticated }) => {
      if (!authenticated) setTokenFailures([]);
    });
    return () => {
      subHealth.unsubscribe();
      subValidated.unsubscribe();
      subAuth.unsubscribe();
    };
  }, []);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setMenuOpen(false);
      }
    };
    if (menuOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [menuOpen]);

  const getInitials = (): string => {
    if (!user?.displayName) return (user?.email?.[0] || '?').toUpperCase();
    const parts = user.displayName.trim().split(/\s+/);
    if (parts.length >= 2) {
      return `${parts[0][0]}${parts[parts.length - 1][0]}`.toUpperCase();
    }
    return user.displayName.slice(0, 2).toUpperCase();
  };

  const { currentTheme, themes, setTheme } = useTheme();
  const [themeOpen, setThemeOpen] = useState(false);
  const themeRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleThemeClickOutside = (e: MouseEvent) => {
      if (themeRef.current && !themeRef.current.contains(e.target as Node)) {
        setThemeOpen(false);
      }
    };
    if (themeOpen) {
      document.addEventListener('mousedown', handleThemeClickOutside);
    }
    return () => document.removeEventListener('mousedown', handleThemeClickOutside);
  }, [themeOpen]);

  const themeIconFor = (id: string) => {
    switch (id) {
      case 'dark': return <Moon size={16} />;
      case 'light': return <Sun size={16} />;
      default: return <Monitor size={16} />;
    }
  };

  const { title: pageTitle, subtitle: pageSubtitle } = usePageHeader();

  return (
    <header className="h-16 flex items-center px-4 border-b border-border bg-background">
      {pageTitle && (
        <div className="min-w-0 mr-4">
          <h1 className="text-lg font-semibold text-foreground truncate leading-tight">
            {pageTitle}
          </h1>
          {pageSubtitle && (
            <p className="text-xs text-muted-foreground truncate leading-tight mt-0.5">
              {pageSubtitle}
            </p>
          )}
        </div>
      )}
      {children}
      <div className="ml-auto flex items-center gap-2">
        {/* Theme selector */}
        <div className="relative" ref={themeRef}>
          <button
            onClick={() => setThemeOpen((prev) => !prev)}
            className="flex items-center gap-1 p-2 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent transition-colors"
            title="Theme"
          >
            <Palette size={16} />
            {themeIconFor(currentTheme ?? 'default')}
          </button>
          {themeOpen && (
            <div className="absolute right-0 top-full mt-1 w-40 rounded-md border border-border bg-popover shadow-lg py-1 z-50">
              {themes.map((theme) => (
                <button
                  key={theme.id}
                  onClick={() => { setTheme(theme.id); setThemeOpen(false); }}
                  className={`flex items-center gap-2 w-full px-3 py-1.5 text-sm transition-colors ${
                    currentTheme === theme.id
                      ? 'text-primary bg-accent/50 font-medium'
                      : 'text-popover-foreground hover:bg-accent'
                  }`}
                >
                  {themeIconFor(theme.id)}
                  <span>{theme.name}</span>
                </button>
              ))}
            </div>
          )}
        </div>

        {tokenFailures.length > 0 && (
          <div className="relative group">
            <button
              onClick={() => { window.location.hash = Urls.Tokens; }}
              className="flex items-center p-1.5 rounded-md text-amber-500 hover:bg-amber-500/10 transition-colors"
              title="Service token issues detected"
            >
              <AlertTriangle size={18} />
            </button>
            <div className="absolute right-0 top-full mt-1 w-72 rounded-md border border-border bg-popover shadow-lg p-3 z-50 hidden group-hover:block">
              <p className="text-xs font-semibold text-popover-foreground mb-2">Token issues ({tokenFailures.length})</p>
              <ul className="space-y-1.5">
                {tokenFailures.map((f) => (
                  <li key={f.id} className="text-xs text-muted-foreground">
                    <span className="font-medium text-popover-foreground">{f.name}</span>
                    <span className="mx-1">—</span>
                    <span className="text-destructive">{f.message}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

      <div className="relative" ref={menuRef}>
        {loading ? (
          <div className="flex items-center gap-2 text-sm">
            <Skeleton className="h-8 w-8 rounded-full" />
            <Skeleton className="h-4 w-24" />
          </div>
        ) : (
          <>
            <button
              onClick={() => setMenuOpen((prev) => !prev)}
              className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
              title="User menu"
            >
              <Avatar className="h-8 w-8">
                {user?.avatarUrl && <AvatarImage src={user.avatarUrl} alt={user?.displayName || user?.email || 'User'} />}
                <AvatarFallback>{getInitials()}</AvatarFallback>
              </Avatar>
              <span>{user?.displayName || user?.email || 'User'}</span>
            </button>

            {menuOpen && (
              <div className="absolute right-0 top-full mt-1 w-48 rounded-md border border-border bg-popover shadow-lg py-1 z-50">
                <button
                  onClick={() => { window.location.hash = Urls.Profile; setMenuOpen(false); }}
                  className="flex items-center gap-2 w-full px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
                >
                  <User size={16} />
                  Profile
                </button>
                <button
                  onClick={() => { window.location.hash = Urls.Tokens; setMenuOpen(false); }}
                  className="flex items-center gap-2 w-full px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
                >
                  <KeyRound size={16} />
                  Tokens
                </button>
                <button
                  onClick={() => { window.location.hash = Urls.SpaceConfiguration; setMenuOpen(false); }}
                  className="flex items-center gap-2 w-full px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
                >
                  <Settings size={16} />
                  Space Configuration
                </button>
                <button
                  onClick={() => { logoutAction(); setMenuOpen(false); }}
                  className="flex items-center gap-2 w-full px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
                >
                  <LogOut size={16} />
                  Logout
                </button>
              </div>
            )}
          </>
        )}
      </div>
      </div>
    </header>
  );
};

Header.displayName = 'Header';
